# Generated by Django 5.0.5 on 2024-05-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_saved', models.DateTimeField(blank=True, null=True)),
                ('character_name', models.TextField(unique=True)),
                ('level', models.SmallIntegerField()),
                ('armor_class', models.SmallIntegerField()),
                ('initiative', models.SmallIntegerField()),
                ('hit_points', models.SmallIntegerField()),
                ('conditions', models.TextField(blank=True, null=True)),
                ('inspiration', models.BooleanField()),
                ('inventory', models.TextField()),
                ('spells', models.TextField(blank=True, null=True)),
                ('speed', models.TextField()),
                ('defenses', models.TextField()),
                ('features', models.TextField()),
                ('traits', models.TextField()),
                ('proficiencies', models.TextField()),
                ('proficiency_value', models.SmallIntegerField()),
                ('languages', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('skill_entry', models.TextField()),
                ('strength_score', models.SmallIntegerField()),
                ('dexterity_score', models.SmallIntegerField()),
                ('constitution_score', models.SmallIntegerField()),
                ('intelligence_score', models.SmallIntegerField()),
                ('wisdom_score', models.SmallIntegerField()),
                ('charisma_score', models.SmallIntegerField()),
            ],
        ),
    ]
